---
title: "CSE 3020 PROJECT"
output: html_notebook
---
```{r}
library(tidyverse)
library(ggplot2)
library(lubridate)
library(data.table)
library(dplyr)
```

```{r}
trips <- fread("final_tripdata.csv")
colnames(trips) <- c("ride_id","rideable_type","started_at","ended_at",
                     "start_station_name","start_station_id",
                     "end_station_name","end_station_id",
                     "start_lat","start_lng","end_lat","end_lng",
                     "member_casual","day_week_start","duration","distance")
```

```{r}
str(trips)
```

```{r}
clean_trips <- trips[distance!=-1 & duration >0]
clean_trips <- clean_trips[, day_week_start:= c("1.Sunday", "2.Monday", "3.Tuesday","4.Wednesday","5.Thursday","6.Friday","7.Saturday")[day_week_start]]
clean_trips$day_week_start
clean_trips <- clean_trips[,day:=as.Date(started_at)][,hour:= hour(started_at)]
str(clean_trips)
clean_trips <- 
  clean_trips[,period:=case_when(
    hour(started_at)>=6 & hour(started_at)<11 ~ '1.Morning',
    hour(started_at)>=11 & hour(started_at)<13 ~ '2.Lunch',
    hour(started_at)>=13 & hour(started_at)<17 ~ '3.Afternoon',
    hour(started_at)>=17 & hour(started_at)<22 ~ '4.Evening',
    hour(started_at)<6 | hour(started_at)>= 22 ~ '5.Night')]

clean_trips <- clean_trips[,duration:=as.double(duration)]

clean_trips <- 
  clean_trips[,.(ride_id, rideable_type, start_station_name, end_station_name, 
                 member_casual, duration, distance, day_week_start, day, hour, period)]

```

```{r}
typeof(clean_trips)
glimpse(clean_trips)
```
# ANALYSIS PART
```{r}
clean_trips[,.(num_rides = .N),by=member_casual]
clean_trips[,.(num_rides = .N),by=rideable_type]
clean_trips[start_station_name != "",.(num_rides = .N), by=start_station_name][order(num_rides,decreasing = TRUE),.SD[1:10]]
clean_trips[end_station_name != "",.(num_rides = .N),
            by=end_station_name][order(num_rides,decreasing = TRUE),.SD[1:10]]
clean_trips[,.(num_rides = .N, 
               min_duration = min(duration), 
               average_duration = mean(duration), 
               max_duration = max(duration))]
clean_trips[,.(num_rides = .N, 
               min_distance = min(distance), 
               average_distance = mean(distance), 
               max_distance = max(distance))]
clean_trips[,.(num_rides = .N),
            day_week_start][,.(day_week_start, num_rides, 
                               percent = num_rides / sum(num_rides)*100)][order(day_week_start)]
clean_trips %>% group_by(member_casual,day_week_start) %>%
  summarise(num_rides = n(), .groups = "drop_last") %>%
  mutate(percent = num_rides / sum(num_rides)*100)


```

# VISUALIZATION
```{r}
clean_trips %>% group_by(day) %>%
  summarise(num_rides = n()) %>%
  ggplot() +
  geom_step(mapping = aes(x = day, y=num_rides)) +
  geom_smooth(mapping = aes(x = day, y=num_rides), method = 'loess', formula = 'y ~ x') +
   theme(axis.text.x = element_text(angle = 45)) +
  labs(title="Number of rides since 2020",
       subtitle = "Total Population",
      x="Date",
      y="Number of rides")
```
```{r}
clean_trips %>% group_by(member_casual, day) %>%
  summarise(num_rides = n(), .groups = "drop_last") %>%
  ggplot() +
  geom_step(mapping = aes(x = day, y=num_rides)) +
  geom_smooth(mapping = aes(x = day, y=num_rides), method = 'loess', formula = 'y ~ x') +
  facet_wrap(~member_casual) +
  theme(axis.text.x = element_text(angle = 45)) +
  labs(title="Number of rides since 2020",
       subtitle = "Distributed by casual users & annual members",
      x="Date",
      y="Number of rides")
```

```{r}
clean_trips %>% group_by(member_casual,day) %>%
  summarise(num_rides = n(),.groups = "drop_last") %>%
  ggplot(aes(x = day, y=num_rides, colour = member_casual)) +
  geom_line() +
  geom_smooth(method = 'loess', formula = 'y ~ x') +
   theme(axis.text.x = element_text(angle = 45)) +
  labs(title="Number of rides since 2020",
       subtitle = "Distributed by casual users & annual members",
      x="Date",
      y="Number of rides",
      color = "Type of user")
```

```{r}
clean_trips[duration<200000,.(dur_rides=mean(duration)),by=day] %>%
  ggplot(aes(x = day, y=dur_rides)) +
  geom_line() +
  geom_smooth(method = 'loess', formula = 'y ~ x') +
   theme(axis.text.x = element_text(angle = 45)) +
  labs(title="Average duration of rides",
       subtitle = "Total Population",
      x="Date",
      y="Duration of rides")
```

```{r}
clean_trips %>% 
  filter(duration < 200000) %>% 
  group_by(member_casual, day) %>%
  summarise(dur_rides = mean(duration), .groups = "drop_last") %>%
  ggplot(aes(x = day, y=dur_rides, color = member_casual)) +
  geom_line() +
  geom_smooth(method = 'loess', formula = 'y ~ x') +
   theme(axis.text.x = element_text(angle = 45)) +
  labs(title="Average duration of rides",
       subtitle = "Distributed by casual users & annual members",
      x="Date",
      y="Duration of rides",
      color="Type of user")
```

```{r}
clean_trips %>% 
  filter(duration < 200000) %>% 
  group_by(member_casual, day_week_start) %>%
  summarise(average_duration = mean(duration), .groups = "drop_last") %>%
  ggplot() +
  geom_col(position = "dodge",
           mapping = aes(x = day_week_start, y = average_duration, fill = member_casual)) +
  theme(axis.text.x = element_text(angle = 45)) +
  labs(title="Average duration of the ride per weekday",
       subtitle = "Distributed by casual users & annual members",
      x="Weekday",
      y="Average duration",
      fill = "Type of user")

```
```{r}
clean_trips %>% 
  filter(duration < 200000) %>% 
  group_by(member_casual,day) %>% 
  summarise(duration = mean(duration), distance = mean(distance), .groups = "drop_last") %>% 
  ggplot(aes(x = duration, y=distance, color = member_casual)) +
  geom_point() +
  labs(title="Duration of the ride vs distance between stations",
       subtitle = "",
      x="Duration",
      y="Distance",
      color = "Type of user")

```

```{r}
cor(clean_trips$duration, clean_trips$distance) # checking the correlation using inbuilt method
```


```{r}
clean_trips %>% 
  group_by(member_casual, day_week_start) %>%
  summarise(average_distance = mean(distance), .groups = "drop_last") %>%
  ggplot() +
  geom_col(position = "dodge",
           mapping = aes(x = day_week_start, y = average_distance, fill = member_casual)) +
  theme(axis.text.x = element_text(angle = 45)) +
  labs(title="Average distance between stations per weekday",
       subtitle = "Distributed by casual users & annual members",
      x="Weekday",
      y="Average distance",
      fill = "Type of user")
```

```{r}
clean_trips%>%
  group_by(day_week_start)%>%
  summarise(num_rides=n()) %>%
  mutate(percent = round(num_rides / sum(num_rides) * 100, digits = 2)) %>%
  ggplot(aes(x = "", y = percent, fill = day_week_start)) +
  geom_col(color = "black") +
  geom_label(aes(label = percent),	position = position_stack(vjust = 0.5),
             show.legend = FALSE) +
  guides(fill = guide_legend(title = "Weekday")) +
  labs(title="Number of rides per weekday (in %)",
      subtitle = "Whole population",
      x="",
      y="Percent") + 
  coord_polar(theta = "y")
```
```{r}
 clean_trips %>% group_by(member_casual, day_week_start) %>%
  summarise(num_rides = n(), .groups = "drop_last")%>%
  mutate(percent = round(num_rides / sum(num_rides) * 100, digits = 2)) %>%
  ggplot(aes(x = "", y = percent, fill = day_week_start)) +
  geom_col(color = "black") +
  facet_wrap(~member_casual) +
  geom_label(aes(label = percent),	position = position_stack(vjust = 0.5),
             show.legend = FALSE) +
  guides(fill = guide_legend(title = "Weekday")) +
  labs(title="Number of rides per weekday (in %)",
      subtitle = "Distributed by casual users & annual members",
      x="",
      y="Percent") + 
  coord_polar(theta = "y")
```
```{r}
clean_trips %>% ggplot() +
  geom_bar(mapping = aes(x = day_week_start)) +
  facet_wrap(~member_casual) +
  theme(axis.text.x = element_text(angle = 45)) +
  labs(title="Number of rides per weekday",
       subtitle = "Distributed by casual users & annual members",
      x="Weekday",
      y="Number of rides")

```

```{r}
clean_trips %>% ggplot() +
  geom_bar(mapping = aes(x = day_week_start, fill = rideable_type)) +
  facet_wrap(~member_casual) +
  theme(axis.text.x = element_text(angle = 45)) +
  labs(title="Number of rides per weekday and type of bike",
       subtitle = "Distributed by casual users & annual members",
      x="Weekday",
      y="Number of rides",
      fill = "Type of bike")
```

```{r}
clean_trips %>% group_by(period) %>%
  summarise(num_rides = n()) %>%
  mutate(percent = round(num_rides / sum(num_rides) * 100, digits = 2)) %>%
  ggplot(aes(x = "", y = percent, fill = period)) +
  geom_col(color = "black") +
  geom_label(aes(label = percent),	position = position_stack(vjust = 0.5),
             show.legend = FALSE) +
  guides(fill = guide_legend(title = "period")) +
  labs(title="Number of rides per period (in %)",
      subtitle = "Whole population",
      x="",
      y="Percent") + 
  coord_polar(theta = "y")
```

```{r}
clean_trips %>% group_by(member_casual, period) %>%
  summarise(num_rides = n(), .groups = "drop_last") %>%
  mutate(percent = round(num_rides / sum(num_rides) * 100, digits = 2)) %>%
  ggplot(aes(x = "", y = percent, fill = period)) +
  geom_col(color = "black") +
  facet_wrap(~member_casual) +
  geom_label(aes(label = percent),	position = position_stack(vjust = 0.5),
             show.legend = FALSE) +
  guides(fill = guide_legend(title = "Period")) +
  labs(title="Number of rides per time of the day (in %)",
      subtitle = "Distributed by casual users & annual members",
      x="",
      y="Percent") + 
  coord_polar(theta = "y")
```

```{r}
clean_trips %>% ggplot() +
  geom_bar(mapping = aes(x = hour, fill = member_casual),position = "dodge") +
  labs(title="Number of rides per hour",
       subtitle = "Distributed by casual users & annual members",
      x="Hour",
      y="Number of rides",
      fill = "Type of user")
```

```{r}
clean_trips %>% ggplot() +
  geom_bar(mapping = aes(x = period, fill = member_casual),position = "dodge") +
  labs(title="Number of rides per time of the day",
       subtitle = "Distributed by casual users & annual members",
      x="Time of the day",
      y="Number of rides",
      fill = "Type of user")
```

```{r}
clean_trips %>% ggplot() +
  geom_bar(mapping = aes(x = day_week_start, fill = period)) +
  facet_wrap(~member_casual) +
  theme(axis.text.x = element_text(angle = 45)) +
  labs(title="Number of rides per weekday and time of the day",
       subtitle = "Distributed by casual users & annual members",
      x="Weekday",
      y="Number of rides",
      fill = "Time of the day")

```

```{r}
stations <- trips[start_station_name != "",.(member_casual, start_station_name,started_at)]
```


```{r}
stationsb <- trips [end_station_name != "",.(member_casual, end_station_name,ended_at)]
  
rm(trips)
colnames(stations) <- c("member_casual","station","time")
colnames(stationsb) <- c("member_casual","station","time")

stations <- rbind(stations, stationsb)
rm(stationsb)
```
```{r}
stations <- 
  stations[, weekday := c("1.Sunday","2.Monday", "3.Tuesday", 
                         "4.Wednesday","5.Thursday", "6.Friday", "7.Saturday")
           [as.POSIXlt(time)$wday + 1]]
```

```{r}
stations <- stations[,time := hour(time)]
```

```{r}
stations %>% 
  group_by(station) %>%
  summarise(num_rides = n()) %>%
  slice_max(num_rides, n = 10)
```

```{r}
selected_stations <- 
  stations %>% 
  filter(member_casual=='casual') %>%
  group_by(station) %>%
  summarise(num_rides = n()) %>%
  slice_max(num_rides, n = 10)
selected_stations <- merge(stations, selected_stations, "station") %>%
  select(station, time, weekday)
rm(stations)
```

```{r}
selected_stations %>% 
  group_by(time, station) %>%
  summarise(num_rides = n(), .groups = "drop_last") %>%
  ggplot(aes(x = time, y=num_rides, color = station)) +
  geom_line() +
  labs(title="Best hour for station",
      x="Hour of the day",
      y="Number of rides",
      color = "Station")
```

```{r}
selected_stations %>%
  group_by(weekday, station) %>%
  summarise(num_rides = n(), .groups = "drop_last") %>%
  ggplot(aes(x = weekday, y=num_rides, color = station)) +
  geom_point() +
   theme(axis.text.x = element_text(angle = 45)) +
  labs(title="Best weekday for station",
      x="Weekday",
      y="Number of rides",
      color = "Station")

```

```{r}

```

